"""Prompts package for the research agent system."""

from .knowledge_acquisition import (
    KNOWLEDGE_EXTRACTION_SYSTEM,
    KNOWLEDGE_EXTRACTION_HUMAN
)

from .qa import (
    QUESTION_GENERATION_SYSTEM,
    QUESTION_GENERATION_HUMAN,
    ANSWER_GENERATION_SYSTEM,
    ANSWER_GENERATION_HUMAN,
    KNOWLEDGE_GAP_SYSTEM,
    KNOWLEDGE_GAP_HUMAN
)

from .synthetic_knowledge import (
    PATTERN_RECOGNITION_SYSTEM,
    PATTERN_RECOGNITION_HUMAN,
    HYPOTHESIS_GENERATION_SYSTEM,
    HYPOTHESIS_GENERATION_HUMAN,
    RELATIONSHIP_INFERENCE_SYSTEM,
    RELATIONSHIP_INFERENCE_HUMAN,
    KNOWLEDGE_SYNTHESIS_SYSTEM,
    KNOWLEDGE_SYNTHESIS_HUMAN
)

from .visual_qa import (
    VISUAL_ELEMENT_DETECTION_SYSTEM,
    VISUAL_ELEMENT_DETECTION_HUMAN,
    SCENE_ANALYSIS_SYSTEM,
    SCENE_ANALYSIS_HUMAN,
    VISUAL_QA_SYSTEM,
    VISUAL_QA_HUMAN
) 