import networkx as nx

# Create a directed graph
G = nx.DiGraph()

# Add nodes (Topics, Herbs, Mechanisms, Approaches) - Cardiovascular Health Section

nodes_cardio = [
    "Cardiovascular Health", "Hawthorn", "Garlic", "Omega-3s", "CoQ10", "Yoga", "Meditation", "Acupuncture", "Qi Gong",
    "Cardiometabolic Network Modulation", "Gut-Heart Axis Optimization",
    "Cardiovascular Support", "Advanced Phytochemistry & Energetic Integration",
    "Sulfur Bioavailability", "Microbiome Modulation", "TCM Syndromes",
    "Specialized Pro-resolving Mediators (SPMs)", "Lipid Raft Dynamics", "Personalized Dosing",
    "Redox Biology", "Mitochondrial Dynamics", "Bioenergetic Profiling",
    "Neurocardiology", "Interoception", "Vagal Tone Variability",
    "Default Mode Network Modulation", "Epigenetic Regulation", "Heart-Brain Synchronization",
    "Neurovascular Coupling", "Microcirculatory Dynamics", "Meridian Theory Refinement",
    "Fascial Network Dynamics", "Biofield Interactions", "Microcirculation Enhancement at Cellular Level",
    "Systems Biology", "Multi-Omics Integration", "Personalized Interventions",
    "Microbial Metabolite Signaling", "Vagal Nerve Stimulation", "Barrier Function Integrity",
    "Holistic Approaches", "Ayurvedic Perspective", "TCM Perspective",
    "Transcriptomics", "Proteomics", "Metabolomics", "Network Pharmacology",
    "Personalized Lifestyle Modifications", "Dietary Modifications", "Stress Reduction Techniques",
    "Emotional Heart-Mind Connection", "Cardiovascular Resilience",
    "Sulfur Chemistry", "Allicin", "Ajoene", "Vinyldithiins", "Hydrogen Sulfide (H2S)",
    "Gut Dysbiosis", "Gut-Heart Axis", "Microbial Metabolites", "Short-Chain Fatty Acids (SCFAs)", "Trimethylamine N-Oxide (TMAO) Pathways",
    "Blood Stasis", "Phlegm Dampness", "Sulfur Compounds", "Garlic Cultivar", "Growing Conditions", "Processing Methods",
    "Metabolites in vivo", "Cardiovascular Risk Markers", "Pungent Nature", "Ayurvedic Dietary Recommendations", "TCM Dietary Recommendations", "Individual Constitutions",
    "Omega-3 Fatty Acids (EPA & DHA)", "Anti-inflammatory Effects", "Triglyceride-Lowering Effects", "Resolvins", "Protectins", "Maresins", "Inflammation Resolution", "Tissue Repair",
    "Cell Membrane Lipid Rafts", "Membrane Fluidity", "Receptor Signaling", "Cellular Function", "Cardiomyocytes", "Endothelial Cells",
    "Genetic Variations", "Fatty Acid Desaturases (FADS Genes)", "Dietary Intake", "Cardiovascular Risk Profiles", "Advanced Lipidomics", "Omega-3 Status",
    "Dietary Framework", "Whole Foods", "Balanced Macronutrients", "Inflammatory Triggers", "Lifestyle Factors", "Environmental Factors",
    "Coenzyme Q10 (CoQ10)", "Mitochondrial Support", "Antioxidant Activity", "Redox Signaling", "Mitochondria", "Cytoplasm", "Cellular Processes", "ATP Production",
    "Mitochondrial Dynamics", "Fusion", "Fission", "Mitochondrial Biogenesis", "Mitophagy",
    "Bioenergetic Profiling Techniques", "Seahorse XF Analyzer", "Mitochondrial Respiration", "Energy Production", "Physiological Conditions", "Pathological Conditions",
    "Mitochondrial Nutrients", "L-Carnitine", "Riboflavin", "Magnesium", "Synergistic Approach", "Mitochondrial Health", "Exercise", "Stress Reduction", "Mitochondrial Toxins",
    "Neurocardiology of Yoga", "Brain-Heart Axis", "Neural Pathways", "Central Nervous System", "Cardiovascular System",
    "Internal Bodily States", "Cardiovascular Autonomic Control", "HRV (Heart Rate Variability) Analysis Techniques", "Nonlinear HRV Analysis", "Frequency Domain Measures",
    "Vagal Tone Dynamics", "Parasympathetic Nervous System Function", "Yoga Styles", "Restorative Yoga", "Yin Yoga", "Pranayama Techniques", "Alternate Nostril Breathing", "Ujjayi Breath",
    "Mindfulness", "Emotional Regulation", "Sense of Purpose", "Connection", "Heart-Mind Coherence",
    "Default Mode Network (DMN)", "Mind-Wandering", "Rumination", "Cardiovascular Outcomes", "Epigenetic Mechanisms", "DNA Methylation", "Histone Modifications",
    "Inflammation", "Stress Response", "Endothelial Function", "Heart Rhythms", "Brain Rhythms", "Neuroimaging Techniques", "fMRI", "EEG", "Brain Activity Changes", "Cardiovascular Parameters",
    "Mindfulness-Based Stress Reduction (MBSR) Programs", "Contemplative Practices", "Emotional Intelligence", "Sustained Heart Health Benefits",
    "Neurovascular Coupling Mechanisms", "Acupuncture Points", "PC6", "HT7", "Vascular Tone", "Blood Flow", "Microcirculation",
    "Advanced Imaging Techniques", "Laser Doppler Flowmetry", "Intravital Microscopy", "Tissue Perfusion", "TCM Meridian Theory", "Bioelectrical Properties", "Bioenergetic Properties", "Acupoints", "Meridians", "Heart Qi Deficiency", "Heart Blood Stasis", "Cardiovascular Risk Factors", "TCM Dietary Therapy", "Herbal Medicine", "Lifestyle Recommendations", "Individual Constitutions", "Cardiovascular Imbalances",
    "Fascial Network Dynamics", "Body-Wide Communication System", "Qi Gong Movements", "Fascial Tension", "Fluid Dynamics", "Mechanotransduction",
    "Biofield Interactions", "Subtle Energetic Effects", "Cellular Communication", "Physiological Processes", "Advanced Microscopy Techniques", "Atomic Force Microscopy", "Super-Resolution Microscopy",
    "Capillary Density", "Red Blood Cell Deformability", "Endothelial Cell Function", "Jing", "Qi", "Shen", "Essence", "Energy", "Spirit",
    "Systems Biology Approach", "Cardiometabolic Health", "Computational Models", "Interconnected Networks", "Cardiovascular Diseases", "Metabolic Diseases", "Multi-Omics Data",
    "Genomics", "Transcriptomics", "Proteomics", "Metabolomics", "Microbiomics", "Dynamic Interplay", "Genes", "Proteins", "Metabolites", "Microbial Communities",
    "Key Network Nodes", "Pathways", "Targeted Interventions", "Pharmacological Approaches", "Non-Pharmacological Approaches", "Precision Medicine Strategies", "Root Causes", "Cardiometabolic Dysfunction", "Global Health Optimization",
    "Gut-Heart Connection", "Intricate Signaling Pathways", "Microbial Metabolite Signaling", "Vagal Nerve Stimulation", "Barrier Function Integrity",
    "Microbial Metabolites", "SCFAs", "Bile Acids", "Tryptophan Metabolites", "Blood Pressure Regulation", "Endothelial Function", "Bidirectional Communication", "Vagal Nerve", "Gut Microbiome Modulation",
    "Vagal Tone", "Autonomic Balance", "Leaky Gut", "Systemic Translocation", "Microbial Products", "LPS", "Peptidoglycans", "Chronic Inflammation",
    "Gut Microbial Profiles", "Microbial Species", "Prebiotic Strategies", "Probiotic Strategies", "Dietary Fiber Optimization", "Fermented Foods", "Gut-Healing Protocols", "Healthy Gut Microbiome", "Cardiovascular Well-being"
]
G.add_nodes_from(nodes_cardio)


# Add edges (Relationships) - Cardiovascular Health Section
edges_cardio = [
    ("Cardiovascular Health", "Hawthorn", {'relation': 'USES'}),
    ("Cardiovascular Health", "Garlic", {'relation': 'USES'}),
    ("Cardiovascular Health", "Omega-3s", {'relation': 'USES'}),
    ("Cardiovascular Health", "CoQ10", {'relation': 'USES'}),
    ("Cardiovascular Health", "Yoga", {'relation': 'USES'}),
    ("Cardiovascular Health", "Meditation", {'relation': 'USES'}),
    ("Cardiovascular Health", "Acupuncture", {'relation': 'USES'}),
    ("Cardiovascular Health", "Qi Gong", {'relation': 'USES'}),
    ("Cardiovascular Health", "Cardiometabolic Network Modulation", {'relation': 'USES'}),
    ("Cardiovascular Health", "Gut-Heart Axis Optimization", {'relation': 'USES'}),

    ("Hawthorn", "Cardiovascular Support", {'relation': 'HAS_TOPIC'}),
    ("Hawthorn", "Advanced Phytochemistry & Energetic Integration", {'relation': 'HAS_TOPIC'}),
    ("Garlic", "Cardiovascular Health", {'relation': 'HAS_TOPIC'}),
    ("Garlic", "Sulfur Bioavailability", {'relation': 'HAS_TOPIC'}),
    ("Garlic", "Microbiome Modulation", {'relation': 'HAS_TOPIC'}),
    ("Garlic", "TCM Syndromes", {'relation': 'HAS_TOPIC'}),
    ("Omega-3s", "Cardiovascular Protection", {'relation': 'HAS_TOPIC'}),
    ("Omega-3s", "Specialized Pro-resolving Mediators (SPMs)", {'relation': 'HAS_TOPIC'}),
    ("Omega-3s", "Lipid Raft Dynamics", {'relation': 'HAS_TOPIC'}),
    ("Omega-3s", "Personalized Dosing", {'relation': 'HAS_TOPIC'}),
    ("CoQ10", "Heart Function", {'relation': 'HAS_TOPIC'}),
    ("CoQ10", "Redox Biology", {'relation': 'HAS_TOPIC'}),
    ("CoQ10", "Mitochondrial Dynamics", {'relation': 'HAS_TOPIC'}),
    ("CoQ10", "Bioenergetic Profiling", {'relation': 'HAS_TOPIC'}),
    ("Yoga", "Cardiovascular Resilience", {'relation': 'HAS_TOPIC'}),
    ("Yoga", "Neurocardiology", {'relation': 'HAS_TOPIC'}),
    ("Yoga", "Interoception", {'relation': 'HAS_TOPIC'}),
    ("Yoga", "Vagal Tone Variability", {'relation': 'HAS_TOPIC'}),
    ("Meditation", "Heart Health", {'relation': 'HAS_TOPIC'}),
    ("Meditation", "Default Mode Network Modulation", {'relation': 'HAS_TOPIC'}),
    ("Meditation", "Epigenetic Regulation", {'relation': 'HAS_TOPIC'}),
    ("Meditation", "Heart-Brain Synchronization", {'relation': 'HAS_TOPIC'}),
    ("Acupuncture", "Cardiovascular Regulation", {'relation': 'HAS_TOPIC'}),
    ("Acupuncture", "Neurovascular Coupling", {'relation': 'HAS_TOPIC'}),
    ("Acupuncture", "Microcirculatory Dynamics", {'relation': 'HAS_TOPIC'}),
    ("Acupuncture", "Meridian Theory Refinement", {'relation': 'HAS_TOPIC'}),
    ("Qi Gong", "Cardiovascular Fitness", {'relation': 'HAS_TOPIC'}),
    ("Qi Gong", "Fascial Network Dynamics", {'relation': 'HAS_TOPIC'}),
    ("Qi Gong", "Biofield Interactions", {'relation': 'HAS_TOPIC'}),
    ("Qi Gong", "Microcirculation Enhancement at Cellular Level", {'relation': 'HAS_TOPIC'}),
    ("Cardiometabolic Network Modulation", "Cardiometabolic Network Modulation", {'relation': 'HAS_TOPIC'}),
    ("Cardiometabolic Network Modulation", "Systems Biology", {'relation': 'HAS_TOPIC'}),
    ("Cardiometabolic Network Modulation", "Multi-Omics Integration", {'relation': 'HAS_TOPIC'}),
    ("Cardiometabolic Network Modulation", "Personalized Interventions", {'relation': 'HAS_TOPIC'}),
    ("Gut-Heart Axis Optimization", "Gut-Heart Axis Optimization", {'relation': 'HAS_TOPIC'}),
    ("Gut-Heart Axis Optimization", "Microbial Metabolite Signaling", {'relation': 'HAS_TOPIC'}),
    ("Gut-Heart Axis Optimization", "Vagal Nerve Stimulation", {'relation': 'HAS_TOPIC'}),
    ("Gut-Heart Axis Optimization", "Barrier Function Integrity", {'relation': 'HAS_TOPIC'}),

    ("Hawthorn", "Ayurvedic Perspective", {'relation': 'APPROACH'}),
    ("Hawthorn", "TCM Perspective", {'relation': 'APPROACH'}),
    ("Hawthorn", "Phytochemistry", {'relation': 'MECHANISM'}),
    ("Hawthorn", "Flavonoids", {'relation': 'MECHANISM'}),
    ("Hawthorn", "Triterpenes", {'relation': 'MECHANISM'}),
    ("Hawthorn", "Amines", {'relation': 'MECHANISM'}),
    ("Hawthorn", "Transcriptomics", {'relation': 'MECHANISM'}),
    ("Hawthorn", "Proteomics", {'relation': 'MECHANISM'}),
    ("Hawthorn", "Metabolomics", {'relation': 'MECHANISM'}),
    ("Hawthorn", "Network Pharmacology", {'relation': 'MECHANISM'}),
    ("Hawthorn", "Holistic Approaches", {'relation': 'APPROACH'}),
    ("Hawthorn", "Personalized Lifestyle Modifications", {'relation': 'APPROACH'}),
    ("Hawthorn", "Dietary Modifications", {'relation': 'APPROACH'}),
    ("Hawthorn", "Stress Reduction Techniques", {'relation': 'APPROACH'}),
    ("Hawthorn", "Yoga", {'relation': 'APPROACH'}),
    ("Hawthorn", "Meditation", {'relation': 'APPROACH'}),
    ("Hawthorn", "Emotional Heart-Mind Connection", {'relation': 'APPROACH'}),

    ("Garlic", "Sulfur Bioavailability", {'relation': 'MECHANISM'}),
    ("Garlic", "Microbiome Modulation", {'relation': 'MECHANISM'}),
    ("Garlic", "TCM Syndromes", {'relation': 'MECHANISM'}),
    ("Garlic", "Sulfur Chemistry", {'relation': 'MECHANISM'}),
    ("Garlic", "Allicin", {'relation': 'MECHANISM'}),
    ("Garlic", "Ajoene", {'relation': 'MECHANISM'}),
    ("Garlic", "Vinyldithiins", {'relation': 'MECHANISM'}),
    ("Garlic", "Hydrogen Sulfide (H2S)", {'relation': 'MECHANISM'}),
    ("Garlic", "Gut Dysbiosis", {'relation': 'MECHANISM'}),
    ("Garlic", "Gut-Heart Axis", {'relation': 'MECHANISM'}),
    ("Garlic", "Microbial Metabolites", {'relation': 'MECHANISM'}),
    ("Garlic", "Short-Chain Fatty Acids (SCFAs)", {'relation': 'MECHANISM'}),
    ("Garlic", "Trimethylamine N-Oxide (TMAO) Pathways", {'relation': 'MECHANISM'}),
    ("Garlic", "Blood Stasis", {'relation': 'MECHANISM'}),
    ("Garlic", "Phlegm Dampness", {'relation': 'MECHANISM'}),
    ("Garlic", "Metabolomics", {'relation': 'MECHANISM'}),
    ("Garlic", "Holistic Approaches", {'relation': 'APPROACH'}),
    ("Garlic", "Ayurvedic Dietary Recommendations", {'relation': 'APPROACH'}),
    ("Garlic", "TCM Dietary Recommendations", {'relation': 'APPROACH'}),

    ("Omega-3s", "Specialized Pro-resolving Mediators (SPMs)", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Lipid Raft Dynamics", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Personalized Dosing", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Omega-3 Fatty Acids (EPA & DHA)", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Anti-inflammatory Effects", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Triglyceride-Lowering Effects", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Resolvins", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Protectins", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Maresins", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Inflammation Resolution", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Tissue Repair", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Cell Membrane Lipid Rafts", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Membrane Fluidity", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Receptor Signaling", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Cellular Function", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Cardiomyocytes", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Endothelial Cells", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Personalized Dosing Strategies", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Genetic Variations", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Fatty Acid Desaturases (FADS Genes)", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Dietary Intake", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Cardiovascular Risk Profiles", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Advanced Lipidomics", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Omega-3 Status", {'relation': 'MECHANISM'}),
    ("Omega-3s", "Holistic Approaches", {'relation': 'APPROACH'}),
    ("Omega-3s", "Dietary Framework", {'relation': 'APPROACH'}),
    ("Omega-3s", "Whole Foods", {'relation': 'APPROACH'}),
    ("Omega-3s", "Balanced Macronutrients", {'relation': 'APPROACH'}),
    ("Omega-3s", "Inflammatory Triggers", {'relation': 'APPROACH'}),
    ("Omega-3s", "Lifestyle Factors", {'relation': 'APPROACH'}),
    ("Omega-3s", "Environmental Factors", {'relation': 'APPROACH'}),

    ("CoQ10", "Redox Biology", {'relation': 'MECHANISM'}),
    ("CoQ10", "Mitochondrial Dynamics", {'relation': 'MECHANISM'}),
    ("CoQ10", "Bioenergetic Profiling", {'relation': 'MECHANISM'}),
    ("CoQ10", "Coenzyme Q10 (CoQ10)", {'relation': 'MECHANISM'}),
    ("CoQ10", "Mitochondrial Support", {'relation': 'MECHANISM'}),
    ("CoQ10", "Antioxidant Activity", {'relation': 'MECHANISM'}),
    ("CoQ10", "Redox Signaling", {'relation': 'MECHANISM'}),
    ("CoQ10", "Mitochondria", {'relation': 'MECHANISM'}),
    ("CoQ10", "Cytoplasm", {'relation': 'MECHANISM'}),
    ("CoQ10", "Cellular Processes", {'relation': 'MECHANISM'}),
    ("CoQ10", "ATP Production", {'relation': 'MECHANISM'}),
    ("CoQ10", "Mitochondrial Dynamics", {'relation': 'MECHANISM'}),
    ("CoQ10", "Fusion", {'relation': 'MECHANISM'}),
    ("CoQ10", "Fission", {'relation': 'MECHANISM'}),
    ("CoQ10", "Mitochondrial Biogenesis", {'relation': 'MECHANISM'}),
    ("CoQ10", "Mitophagy", {'relation': 'MECHANISM'}),
    ("CoQ10", "Cardiomyocytes", {'relation': 'MECHANISM'}),
    ("CoQ10", "Bioenergetic Profiling Techniques", {'relation': 'MECHANISM'}),
    ("CoQ10", "Seahorse XF Analyzer", {'relation': 'MECHANISM'}),
    ("CoQ10", "Mitochondrial Respiration", {'relation': 'MECHANISM'}),
    ("CoQ10", "Energy Production", {'relation': 'MECHANISM'}),
    ("CoQ10", "Physiological Conditions", {'relation': 'MECHANISM'}),
    ("CoQ10", "Pathological Conditions", {'relation': 'MECHANISM'}),
    ("CoQ10", "Mitochondrial Nutrients", {'relation': 'MECHANISM'}),
    ("CoQ10", "L-Carnitine", {'relation': 'MECHANISM'}),
    ("CoQ10", "Riboflavin", {'relation': 'MECHANISM'}),
    ("CoQ10", "Magnesium", {'relation': 'MECHANISM'}),
    ("CoQ10", "Synergistic Approach", {'relation': 'MECHANISM'}),
    ("CoQ10", "Holistic Approaches", {'relation': 'APPROACH'}),
    ("CoQ10", "Lifestyle Modifications", {'relation': 'APPROACH'}),
    ("CoQ10", "Mitochondrial Health", {'relation': 'APPROACH'}),
    ("CoQ10", "Exercise", {'relation': 'APPROACH'}),
    ("CoQ10", "Stress Reduction", {'relation': 'APPROACH'}),
    ("CoQ10", "Mitochondrial Toxins", {'relation': 'APPROACH'}),

    ("Yoga", "Neurocardiology", {'relation': 'MECHANISM'}),
    ("Yoga", "Interoception", {'relation': 'MECHANISM'}),
    ("Yoga", "Vagal Tone Variability", {'relation': 'MECHANISM'}),
    ("Yoga", "Neurocardiology of Yoga", {'relation': 'MECHANISM'}),
    ("Yoga", "Brain-Heart Axis", {'relation': 'MECHANISM'}),
    ("Yoga", "Neural Pathways", {'relation': 'MECHANISM'}),
    ("Yoga", "Central Nervous System", {'relation': 'MECHANISM'}),
    ("Yoga", "Cardiovascular System", {'relation': 'MECHANISM'}),
    ("Yoga", "Interoception", {'relation': 'MECHANISM'}),
    ("Yoga", "Internal Bodily States", {'relation': 'MECHANISM'}),
    ("Yoga", "Cardiovascular Autonomic Control", {'relation': 'MECHANISM'}),
    ("Yoga", "HRV (Heart Rate Variability) Analysis Techniques", {'relation': 'MECHANISM'}),
    ("Yoga", "Nonlinear HRV Analysis", {'relation': 'MECHANISM'}),
    ("Yoga", "Frequency Domain Measures", {'relation': 'MECHANISM'}),
    ("Yoga", "Vagal Tone Dynamics", {'relation': 'MECHANISM'}),
    ("Yoga", "Parasympathetic Nervous System Function", {'relation': 'MECHANISM'}),
    ("Yoga", "Yoga Styles", {'relation': 'MECHANISM'}),
    ("Yoga", "Restorative Yoga", {'relation': 'MECHANISM'}),
    ("Yoga", "Yin Yoga", {'relation': 'MECHANISM'}),
    ("Yoga", "Pranayama Techniques", {'relation': 'MECHANISM'}),
    ("Yoga", "Alternate Nostril Breathing", {'relation': 'MECHANISM'}),
    ("Yoga", "Ujjayi Breath", {'relation': 'MECHANISM'}),
    ("Yoga", "Holistic Approaches", {'relation': 'APPROACH'}),
    ("Yoga", "Mindfulness", {'relation': 'APPROACH'}),
    ("Yoga", "Emotional Regulation", {'relation': 'APPROACH'}),
    ("Yoga", "Sense of Purpose", {'relation': 'APPROACH'}),
    ("Yoga", "Connection", {'relation': 'APPROACH'}),
    ("Yoga", "Heart-Mind Coherence", {'relation': 'APPROACH'}),

    ("Meditation", "Default Mode Network Modulation", {'relation': 'MECHANISM'}),
    ("Meditation", "Epigenetic Regulation", {'relation': 'MECHANISM'}),
    ("Meditation", "Heart-Brain Synchronization", {'relation': 'MECHANISM'}),
    ("Meditation", "Default Mode Network (DMN)", {'relation': 'MECHANISM'}),
    ("Meditation", "Mind-Wandering", {'relation': 'MECHANISM'}),
    ("Meditation", "Rumination", {'relation': 'MECHANISM'}),
    ("Meditation", "Stress Reduction", {'relation': 'MECHANISM'}),
    ("Meditation", "Cardiovascular Outcomes", {'relation': 'MECHANISM'}),
    ("Meditation", "Epigenetic Mechanisms", {'relation': 'MECHANISM'}),
    ("Meditation", "DNA Methylation", {'relation': 'MECHANISM'}),
    ("Meditation", "Histone Modifications", {'relation': 'MECHANISM'}),
    ("Meditation", "Inflammation", {'relation': 'MECHANISM'}),
    ("Meditation", "Stress Response", {'relation': 'MECHANISM'}),
    ("Meditation", "Endothelial Function", {'relation': 'MECHANISM'}),
    ("Meditation", "Heart-Brain Synchronization", {'relation': 'MECHANISM'}),
    ("Meditation", "Heart Rhythms", {'relation': 'MECHANISM'}),
    ("Meditation", "Brain Rhythms", {'relation': 'MECHANISM'}),
    ("Meditation", "Neuroimaging Techniques", {'relation': 'MECHANISM'}),
    ("Meditation", "fMRI", {'relation': 'MECHANISM'}),
    ("Meditation", "EEG", {'relation': 'MECHANISM'}),
    ("Meditation", "Brain Activity Changes", {'relation': 'MECHANISM'}),
    ("Meditation", "Cardiovascular Parameters", {'relation': 'MECHANISM'}),
    ("Meditation", "Holistic Approaches", {'relation': 'APPROACH'}),
    ("Meditation", "Mindfulness-Based Stress Reduction (MBSR) Programs", {'relation': 'APPROACH'}),
    ("Meditation", "Contemplative Practices", {'relation': 'APPROACH'}),
    ("Meditation", "Emotional Intelligence", {'relation': 'APPROACH'}),
    ("Meditation", "Sustained Heart Health Benefits", {'relation': 'APPROACH'}),

    ("Acupuncture", "Neurovascular Coupling", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Microcirculatory Dynamics", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Meridian Theory Refinement", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Neurovascular Coupling Mechanisms", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Acupuncture Points", {'relation': 'MECHANISM'}),
    ("Acupuncture", "PC6", {'relation': 'MECHANISM'}),
    ("Acupuncture", "HT7", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Neural Pathways", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Vascular Tone", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Blood Flow", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Microcirculation", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Cardiovascular System", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Advanced Imaging Techniques", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Laser Doppler Flowmetry", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Intravital Microscopy", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Microcirculatory Dynamics", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Tissue Perfusion", {'relation': 'MECHANISM'}),
    ("Acupuncture", "TCM Meridian Theory", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Bioelectrical Properties", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Bioenergetic Properties", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Acupoints", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Meridians", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Heart Health", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Personalized Acupuncture Protocols", {'relation': 'MECHANISM'}),
    ("Acupuncture", "TCM Pattern Differentiation", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Heart Qi Deficiency", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Heart Blood Stasis", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Cardiovascular Risk Factors", {'relation': 'MECHANISM'}),
    ("Acupuncture", "Holistic Approaches", {'relation': 'APPROACH'}),
    ("Acupuncture", "TCM Dietary Therapy", {'relation': 'APPROACH'}),
    ("Acupuncture", "Herbal Medicine", {'relation': 'APPROACH'}),
    ("Acupuncture", "Lifestyle Recommendations", {'relation': 'APPROACH'}),
    ("Acupuncture", "Individual Constitutions", {'relation': 'APPROACH'}),
    ("Acupuncture", "Cardiovascular Imbalances", {'relation': 'APPROACH'}),

    ("Qi Gong", "Fascial Network Dynamics", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Biofield Interactions", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Microcirculation Enhancement at Cellular Level", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Fascial Network Dynamics", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Body-Wide Communication System", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Qi Gong Movements", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Fascial Tension", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Fluid Dynamics", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Mechanotransduction", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Cardiovascular Function", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Biofield Interactions", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Subtle Energetic Effects", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Cellular Communication", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Physiological Processes", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Advanced Microscopy Techniques", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Atomic Force Microscopy", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Super-Resolution Microscopy", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Microcirculation", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Cellular Level", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Subcellular Level", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Capillary Density", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Red Blood Cell Deformability", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Endothelial Cell Function", {'relation': 'MECHANISM'}),
    ("Qi Gong", "Holistic Approaches", {'relation': 'APPROACH'}),
    ("Qi Gong", "Mindful Movement Practices", {'relation': 'APPROACH'}),
    ("Qi Gong", "Breathing Exercises", {'relation': 'APPROACH'}),
    ("Qi Gong", "Jing", {'relation': 'APPROACH'}),
    ("Qi Gong", "Qi", {'relation': 'APPROACH'}),
    ("Qi Gong", "Shen", {'relation': 'APPROACH'}),
    ("Qi Gong", "Essence", {'relation': 'APPROACH'}),
    ("Qi Gong", "Energy", {'relation': 'APPROACH'}),
    ("Qi Gong", "Spirit", {'relation': 'APPROACH'}),

    ("Cardiometabolic Network Modulation", "Systems Biology", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Multi-Omics Integration", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Personalized Interventions", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Systems Biology Approach", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Cardiometabolic Health", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Computational Models", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Interconnected Networks", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Cardiovascular Diseases", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Metabolic Diseases", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Multi-Omics Data", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Genomics", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Transcriptomics", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Proteomics", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Metabolomics", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Microbiomics", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Dynamic Interplay", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Genes", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Proteins", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Metabolites", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Microbial Communities", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Key Network Nodes", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Pathways", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Targeted Interventions", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Pharmacological Approaches", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Non-Pharmacological Approaches", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Personalized Interventions", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Cardiometabolic Risk Profiles", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Network Signatures", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Precision Medicine Strategies", {'relation': 'MECHANISM'}),
    ("Cardiometabolic Network Modulation", "Holistic Approaches", {'relation': 'APPROACH'}),
    ("Cardiometabolic Network Modulation", "Lifestyle Interventions", {'relation': 'APPROACH'}),
    ("Cardiometabolic Network Modulation", "Dietary Interventions", {'relation': 'APPROACH'}),
    ("Cardiometabolic Network Modulation", "Mind-Body Interventions", {'relation': 'APPROACH'}),
    ("Cardiometabolic Network Modulation", "Root Causes", {'relation': 'APPROACH'}),
    ("Cardiometabolic Network Modulation", "Cardiometabolic Dysfunction", {'relation': 'APPROACH'}),
    ("Cardiometabolic Network Modulation", "Global Health Optimization", {'relation': 'APPROACH'}),

    ("Gut-Heart Axis Optimization", "Gut-Heart Connection", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Intricate Signaling Pathways", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Microbial Metabolite Signaling", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Vagal Nerve Stimulation", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Barrier Function Integrity", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Gut-Heart Connection", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Intricate Signaling Pathways", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Microbial Metabolites", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "SCFAs", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Bile Acids", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Tryptophan Metabolites", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Cardiovascular Function", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Blood Pressure Regulation", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Inflammation", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Endothelial Function", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Bidirectional Communication", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Vagal Nerve", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Gut Microbiome Modulation", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Vagal Tone", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Autonomic Balance", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Gut Barrier Function Integrity", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Leaky Gut", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Systemic Translocation", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Microbial Products", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "LPS", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Peptidoglycans", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Chronic Inflammation", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Cardiovascular Disease", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Advanced Microbiome Sequencing", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Metabolomics Techniques", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Gut Microbial Profiles", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Microbial Species", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Metabolites", {'relation': 'MECHANISM'}),
    ("Gut-Heart Axis Optimization", "Holistic Approaches", {'relation': 'APPROACH'}),
    ("Gut-Heart Axis Optimization", "Prebiotic Strategies", {'relation': 'APPROACH'}),
    ("Gut-Heart Axis Optimization", "Probiotic Strategies", {'relation': 'APPROACH'}),
    ("Gut-Heart Axis Optimization", "Dietary Fiber Optimization", {'relation': 'APPROACH'}),
    ("Gut-Heart Axis Optimization", "Fermented Foods", {'relation': 'APPROACH'}),
    ("Gut-Heart Axis Optimization", "Gut-Healing Protocols", {'relation': 'APPROACH'}),
    ("Gut-Heart Axis Optimization", "Healthy Gut Microbiome", {'relation': 'APPROACH'}),
    ("Gut-Heart Axis Optimization", "Gut-Heart Axis", {'relation': 'APPROACH'}),
    ("Gut-Heart Axis Optimization", "Cardiovascular Well-being", {'relation': 'APPROACH'}),

]

G.add_edges_from(edges_cardio)


print("Knowledge Graph - Cardiovascular Health Section (Nodes and Edges):")
print("\nNodes:")
print(list(G.nodes))
print("\nEdges:")
for u, v, data in G.edges(data=True):
    print(f"({u}) -[:{data['relation']}]-> ({v})")