"""Synthetic knowledge generation prompts package."""

from .generation import (
    PATTERN_RECOGNITION_SYSTEM,
    PATTERN_RECOGNITION_HUMAN,
    HYPOTHESIS_GENERATION_SYSTEM,
    HYPOTHESIS_GENERATION_HUMAN,
    RELATIONSHIP_INFERENCE_SYSTEM,
    RELATIONSHIP_INFERENCE_HUMAN,
    KNOWLEDGE_SYNTHESIS_SYSTEM,
    KNOWLEDGE_SYNTHESIS_HUMAN
) 